### ISSUE TITLE
Download a vcf files 

### ISSUE THREAD

**Issue by Dr-Sumayah** [apetkau/genomics-data-index#109]
Hello ,

I am trying to use [CScape a cancer-predictor](http://cscape.biocompute.org.uk)

To run CScape queries locally, I need to download the some files and run the query script . 

First: I downloaded [tabix](https://sourceforge.net/projects/samtools/files/tabix) as a perquisite.

Next: I tried many many times to download the (VCF) files with no luck here are the files: 
[cscape_coding.vcf.gz (6GB) ](http://cscape.biocompute.org.uk)
[cscape_noncoding.vcf.gz (51GB)](http://cscape.biocompute.org.uk) 

I got only about  67KM from the file  

I am using macOS .

**Comment by apetkau** [comment]
Hello @Dr-Sumayah , did you perhaps mean to send this to the developers of CScape? I am not involved with that project and have no control over the files you are trying to download.

I hope you are able to sort this out.

**Comment by Dr-Sumayah** [comment]
Thank you @apetkau  for your answer.

I did tell them but they believe that the files are fine, so here I am trying to figure out what is the problem. Could you kindly try and download them ? 
I want to see if it is an issue in my computer
